#pragma once

#define PUFF_VERSION 0

#define PUFF_MAJOR_VERSION    (PUFF_VERSION / 100000)
#define PUFF_MINOR_VERSION    (PUFF_VERSION / 100 % 1000)
#define PUFF_SUBMINOR_VERSION (PUFF_VERSION % 100)
